--- 
framework: 
  AdminMode: 0
  ApplicationClass: TestApp::Plugin::SinglePage
  ApplicationName: TestApp::Plugin::SinglePage
  ApplicationUUID: DC3B58E4-4F3C-11DC-9ECB-E5DB6F105773
  ConfigFileVersion: 2
  Database: 
    CheckSchema: 1
    Database: testapp_plugin_singlepage
    Driver: SQLite
    Host: localhost
    Password: ''
    RecordBaseClass: Jifty::DBI::Record::Cachable
    RecordUUIDs: active
    User: ''
    Version: 0.0.1
  DevelMode: 0
  L10N: 
    PoDir: share/po
  LogLevel: INFO
  Mailer: Sendmail
  MailerArgs: []

  Plugins: 
    - AdminUI: {}
    - CompressedCSSandJS: {}
    - ErrorTemplates: {}
    - Halo: {}
    - LetMe: {}
    - OnlineDocs: {}
    - REST: {}
    - SinglePage: {}
    - SkeletonApp: {}
    - User: {}

  PubSub: 
    Backend: Memcached
    Enable: ~
  SkipAccessControl: 0
  TemplateClass: TestApp::Plugin::SinglePage::View
  Web: 
    BaseURL: http://localhost
    DataDir: var/mason
    Globals: []

    MasonConfig: 
      autoflush: 0
      default_escape_flags: h
      error_format: text
      error_mode: fatal
    Port: 8888
    ServeStaticFiles: 1
    StaticRoot: share/web/static
    TemplateRoot: share/web/templates
