---
author: ~
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: Perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Jifty
no_index:
  directory:
    - debian
    - doc
    - examples
    - inc
    - share
    - t
  package:
    - DB
recommends:
  Apache2::Const: 0
  Class::Accessor::Named: 0
  DBD::SQLite: 0
  Data::Dump::Streamer: 0
  Devel::Cover: 0
  Email::Abstract: 0
  Module::CoreList: 0
  Module::Install::Admin: 0.50
  Module::Refresh: 0.09
  Net::Server::Fork: 0
  Net::Server::PreFork: 0
  Pod::Simple: 0
  Test::Base: 0.44
  Test::Email: 0
  Test::HTML::Lint: 0
  Test::HTTP::Server::Simple: 0.10
  Test::MockModule: 0.05
  Test::MockObject: 1.07
  Test::WWW::Declare: 0.01
requires:
  Any::Moose: 0
  App::CLI: 0.08
  CGI: 3.30
  CGI::Cookie::Splitter: 0
  CGI::Simple: 0
  CSS::Squish: 0.07
  Cache::Cache: 0
  Calendar::Simple: 0
  Carp::Clan: 0
  Class::Accessor: 0
  Class::Container: 0
  Class::Data::Inheritable: 0
  Class::Inspector: 1.2
  Class::Trigger: 0.13
  Clone: 0.27
  Compress::Zlib: 0
  Crypt::CBC: 0
  Crypt::Rijndael: 0
  DBD::SQLite: 1.11
  DBI: 0
  Data::Page: 0
  Data::UUID: 0
  Date::Manip: 0
  DateTime: 0
  DateTime::Locale: 0
  Email::Folder: 0
  Email::LocalDelivery: 0.217
  Email::MIME: 1.861
  Email::MIME::ContentType: 1.012
  Email::MIME::CreateHTML: 0
  Email::MIME::Creator: 1.45
  Email::MIME::Modifier: 1.442
  Email::Send: 2.10
  Email::Simple: 2.003
  Email::Simple::Creator: 1.4
  Exception::Class: 0
  Exporter::Lite: 0
  File::Find::Rule: 0
  File::MMagic: 0
  File::ShareDir: 1.00
  File::Spec: 3.14
  File::Temp: 0.15
  HTML::Entities: 0
  HTML::Lint: 0
  HTML::Mason: 1.3101
  HTML::Mason::Plugin: 0
  HTTP::Cookies: 0
  HTTP::Date: 0
  HTTP::Server::Simple: 0.35
  HTTP::Server::Simple::Recorder: 0
  Hash::Merge: 0
  Hook::LexWrap: 0
  IPC::PubSub: 0.23
  IPC::Run3: 0
  JSON::Syck: 0.29
  Jifty::DBI: 0.58
  LWP::UserAgent: 0
  List::MoreUtils: 0
  Locale::Maketext::Extract: 0.35
  Locale::Maketext::Lexicon: 0.77
  Log::Log4perl: 1.11
  MIME::Types: 0
  Module::CoreList: 0
  Module::Pluggable: 3.7
  Module::Pluggable::Object: 0
  Module::Refresh: 0
  Module::ScanDeps: 0
  Object::Declare: 0.13
  Params::Validate: 0
  Plack: 0
  Plack::Request: 0
  SQL::ReservedWords: 0
  SUPER: 0
  Scalar::Defer: 0.12
  Shell::Command: 0
  String::BufferStack: 1.12
  String::Koremutake: 0
  Template::Declare: 0.36
  Test::Base: 0
  Test::LongString: 0
  Test::More: 0.62
  Test::Pod::Coverage: 0
  Test::Script::Run: 0.03
  Test::WWW::Mechanize: 1.04
  Test::WWW::Selenium: 1.18
  UNIVERSAL::require: 0
  URI: 1.31
  URI::Escape: 0
  WWW::Mechanize: 1.51
  XML::Simple: 0
  XML::Writer: 0.601
  XML::XPath: 0
  YAML: 0.35
  YAML::Syck: 0.71
  perl: 5.8.3
  version: 0
version: 0.91117
