--- 
framework: 
  AdminMode: 0
  ApplicationClass: TestApp::Plugin::ActorMetadata
  ApplicationName: TestApp::Plugin::ActorMetadata
  ApplicationUUID: C4418A2E-DE0B-11DD-96DC-F9E9C3E98ACD
  ConfigFileVersion: 4
  Database: 
    AutoUpgrade: 1
    CheckSchema: 1
    Database: testapp_plugin_actormetadata
    Driver: SQLite
    Host: localhost
    Password: ''
    RecordBaseClass: Jifty::DBI::Record::Cachable
    User: ''
    Version: 0.0.1
  DevelMode: 0
  L10N: 
    PoDir: share/po
  LogLevel: INFO
  Mailer: Sendmail
  MailerArgs: []

  Plugins: 
    - AdminUI: {}
    - Authentication::Password: {}
    - CompressedCSSandJS: {}
    - ErrorTemplates: {}
    - Halo: {}
    - LetMe: {}
    - OnlineDocs: {}
    - REST: {}
    - SkeletonApp: {}
    - User: {}

  PubSub: 
    Backend: Memcached
    Enable: ~
  SkipAccessControl: 0
  TemplateClass: TestApp::Plugin::ActorMetadata::View
  View: 
    Handlers: 
      - Jifty::View::Static::Handler
      - Jifty::View::Declare::Handler
      - Jifty::View::Mason::Handler
  Web: 
    BaseURL: http://localhost
    DataDir: var/mason
    Globals: []

    MasonConfig: 
      autoflush: 1
      default_escape_flags: h
      error_format: text
      error_mode: fatal
    Port: 8888
    ServeStaticFiles: 1
    StaticRoot: share/web/static
    TemplateRoot: share/web/templates
